### ISSUE TITLE
Issue-1

### ISSUE THREAD

**Issue by ndikumanaisaie** [Chrissiku/Portfolio-mobile#8]
@bobb-rob
- [x] kindly add alt attribute value to your image(HTML line 189)
- [x] after merging your branch with the main branch I think it is a good practice to delete the branch.
- [x] please use CSS variables wherever possible to make your code maintainable and avoid unnecessary repetition of code.

@ndikumanaisaie
- [x] kindly add animations to your website to improve its look and feel.

**Comment by Chrissiku** [comment]
Thank you for all
